### ISSUE TITLE
Crashes when run

### ISSUE THREAD

**Issue by andrewb-ms** [jmkhael/faas-artist#3]
Am getting this error when using Postman to send a file:

```
exit status 1
Traceback (most recent call last):
  File "index.py", line 16, in <module>
    handler.handle(st)
  File "/root/function/handler.py", line 221, in handle
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/root/function/handler.py", line 197, in main
    os.path.expanduser(FLAGS.input_image)), 0)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_utils.py", line 250, in load_np_image
    image = scipy.misc.imread(f.name)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 156, in imread
    im = Image.open(name)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
IOError: cannot identify image file '/tmp/tmp1UgAmf'
```

**Comment by andrewb-ms** [comment]
This is when bound to a public IP
